// noinspection JSUnusedGlobalSymbols

export enum Permission {
    ROLE_GET = "ROLE_GET",
    ROLE_GET_PERMISSIONS = "ROLE_GET_PERMISSIONS",
    ROLE_CREATE = "ROLE_CREATE",
    ROLE_UPDATE_PERMISSIONS = "ROLE_UPDATE_PERMISSIONS",
    ROLE_UPDATE_STATUS = "ROLE_UPDATE_STATUS",
    ROLE_DELETE = "ROLE_DELETE",
    ROLE_WIPE = "ROLE_WIPE",

    USER_GET = "USER_GET",
    USER_UPDATE = "USER_UPDATE",
    USER_UPDATE_ROLE = "USER_UPDATE_ROLE",
    USER_UPDATE_STATUS = "USER_UPDATE_STATUS",
    USER_DELETE = "USER_DELETE",
    USER_WIPE = "USER_WIPE",

    COURSE_GET = "COURSE_GET",
    COURSE_CREATE = "COURSE_CREATE",
    COURSE_UPDATE = "COURSE_UPDATE",
    COURSE_UPDATE_STATUS = "COURSE_UPDATE_STATUS",
    COURSE_DELETE = "COURSE_DELETE",
    COURSE_WIPE = "COURSE_WIPE",

    MODULE_GET = "MODULE_GET",
    MODULE_CREATE = "MODULE_CREATE",
    MODULE_UPDATE = "MODULE_UPDATE",
    MODULE_UPDATE_STATUS = "MODULE_UPDATE_STATUS",
    MODULE_DELETE = "MODULE_DELETE",
    MODULE_WIPE = "MODULE_WIPE",
}
