on:
  push:
    branches: [ dev, test-workflow ]
  pull_request:
    branches: [ dev, test-workflow ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Project
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build --if-present



#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#
#    - name: cd env/dev/api/lectures/
#      uses: garygrossgarten/github-action-ssh@release
#      with:
#        command: ls -a
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USERNAME }}
#        password: ${{ secrets.PASSWORD }}
#
#    - name: git clone u://r/l --branch x
#      uses: garygrossgarten/github-action-ssh@release
#      with:
#        command: ls -a
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USERNAME }}
#        password: ${{ secrets.PASSWORD }}
