on:
  push:
    branches: [ dev, test-workflow ]
  pull_request:
    branches: [ dev, test-workflow ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - run: npm install --legacy-peer-deps
      - run: npm run build --if-present

      - name: Copy API dependencies to development environment
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          rm: true
          source: node_modules/*
          target: ~/env/dev/api/source

      - name: Copy source to development environment
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: dist/*
          target: ~/env/dev/api/source

#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#
#    - name: cd env/dev/api/lectures/
#      uses: garygrossgarten/github-action-ssh@release
#      with:
#        command: ls -a
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USERNAME }}
#        password: ${{ secrets.PASSWORD }}
#
#    - name: git clone u://r/l --branch x
#      uses: garygrossgarten/github-action-ssh@release
#      with:
#        command: ls -a
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USERNAME }}
#        password: ${{ secrets.PASSWORD }}
